# Resumen 

## Utilización de datos satelitales para la evaluación y mejora de los pronósticos numéricos en alta resolución a muy corto plazo {.unnumbered}


En la Argentina, los fenómenos meteorológicos extremos producen cuantiosas pérdidas humanas y materiales. Muchos de estos fenómenos, por ejemplo tornados, ráfagas intensas, precipitaciones extremas en cortos períodos de tiempo, granizo de gran tamaño y actividad eléctrica, están asociados a la ocurrencia de convección profunda. Es por tal motivo necesario avanzar en el conocimiento de estos fenómenos y en la capacidad de pronosticar la ocurrencia de los mismos. El pronóstico de los fenómenos severos es un desafío científico y tecnológico muy complejo debido a la predictibilidad limitada en la mesoescala y a la dificultad de conocer o diagnosticar el estado de la atmósfera en escalas espaciales pequeñas y tiempos cortos (por ejemplo de 1 a 10 km y del orden de los minutos). La asimilación de datos (AD) en la mesoescala es un enfoque que puede proporcionar condiciones iniciales adecuadas para generar pronósticos numéricos de alta resolución y, por tanto, es un área de estudio en constante evolución. 

Para que los métodos de asimilación de datos tengan éxito, deben utilizarse redes de observación con suficiente resolución temporal y espacial capaces de captar la variabilidad de la mesoescala. La relativa escasez de observaciones convencionales en Sudamérica supone un importante desafío que puede ser resuelto con el uso de otras fuentes de observaciones como estaciones de superficie automáticas, vientos derivados de observaciones satelitales y radiancias de satélites polares y geoestacionarios en cielo claro. En este contexto, este trabajo de tésis busca cuantificar y comparar el impacto de cada uno de los conjuntos de datos en un sistema de asimilación de mesoescala. 

El estudio de la asimilación de radiancias a nivel regional cobra aún mayor importancia en Sudamérica ya que no se conocen estudios realizados previamente y la red de observaciones convencionales tiene baja resolución espacial. Por esta razón, en este trabajo se hace especial énfasis en la asimilación directa de radiancias y los controles de calidad necesarios para trabajar con estas observaciones. En primer lugar se estudia el impacto de la asimilación de observaciones de satélites polares con sensores sensibles al espectro infrarrojo y microondas. Y en segundo lugar, se estudia la implementación de la asimilación de observaciones del satélite geoestacionario GOES-16 y el impacto de asimilar observaciones en alta resolución espacial y temporal en un contexto regional. 

Para alcanzar los objetivos de esta tésis, se realizaron distintos experimentos de asimilación de datos aplicados a un estudio de caso de un SCM que se desarrolló sobre el sur de Sudamérica durante el 22 y 23 de noviembre de 2018 durante el período de observación intensiva de la campaña de campo RELAMPAGO. Se utilizó el sistema WRF-GSI-LETFK para la generación de los experimentos de actualización frecuente y basados en ensambles. Mientras que el modelo WRF es uno de los más utilizados y en constante avance, con importantes antecedentes en Argentina, el sistema de asimilación GSI y en particular su versión de LETKF, no ha sido probado en Argentina y es uno de los aportes originales de esta tesis. 

Los resultados obtenidos muestran que la asimilación de observaciones con alta frecuencia temporal y espacial genera un importante impacto en la capa límite planetaria corrigiendo el bias cálido y seco presente en el modelo generando un mejor desarrollo de la convección profunda y la precipitación para el caso de estudio. La asimilación de las observaciones de radiancia produjo un mejor desarrollo de la convección conduciendo a un aumento de la precipitación acumulada. El pronóstico por ensambles inicializado a partir de cada experimento también mostró mejoras en la representación de la precipitación. Finalmente la implementación de la asimilación de observaciones de GOES-16 mostró ser adecuada produciendo pronósticos de precipitación más cercanos a lo observado. En particular los experimentos de sensibilidad generados para analizar el impacto de asimilar observaciones de los tres canales de vapor de agua mostraron que el canal 10, asociado al contenido de vapor de agua en niveles bajos, aporta casi tanta información como asimilar simultaneamente los 3 canales de vapor de agua, particularmente cuando las observaciones son asimiladas utilizando una resolución espacial similar a la del modelo (10 km). 


**Palabras claves:** Asimilación de datos, Mesoescala, Observaciones convencionales, Observaciones de satélite, Pronósticos 

# Abstract {.unnumbered}

## Use of satellite data for the evaluation and improvement of short-term high-resolution numerical forecasts {.unnumbered}


In Argentina, extreme weather events cause considerable human and material losses. Many of these phenomena, such as tornadoes, intense gusts, extreme rainfall in short periods of time, large hail, and ligtning, are associated with deep convection. It is, therefore, necessary to advance in the knowledge of these phenomena and in the ability to forecast their occurrence. The forecasting of severe phenomena is a very complex scientific and technological challenge due to the limited predictability at the mesoscale and the difficulty of knowing or diagnosing the state of the atmosphere at small spatial scales and short times (for example, from 1 to 10 km and in the order of minutes). Data assimilation (DA) at the mesoscale is an approach that can provide suitable initial conditions for generating high-resolution numerical forecasts and is therefore an evolving area of study. 

For data assimilation methods to be successful, observational networks with a sufficient temporal and spatial resolution capable of capturing mesoscale variability must be used. The relative scarcity of conventional observations in South America poses an important challenge that can be solved with the use of other sources of observations such as automatic weather stations, winds derived from satellite observations, and radiances from polar and geostationary satellites in clear sky. In this context, this thesis work sought to quantify and compare the impact of each of the data sets in a mesoscale assimilation system. 

The study of radiance assimilation at the regional level is even more important in South America since no previous studies have been carried out and the conventional observation network has low spatial resolution. For this reason, special emphasis is placed on direct radiance assimilation and the quality controls necessary to work with these observations. First, the impact of the assimilation of polar satellite observations with sensors sensitive to the infrared and microwave spectrum is studied. Secondly, we study the implementation of the assimilation of observations from the GOES-16 geostationary satellite and the impact of assimilating observations at high spatial and temporal resolution in a regional context. 

To achieve the objectives of this thesis, different data assimilation experiments were performed for a case study of an MCS that developed over southern South America during November 22-23, 2018 during the intensive observing period of the RELAMPAGO field campaign. The WRF-GSI-LETFK system was used for the generation of frequently update ensemble-based experiments. While the WRF model is one of the most used and in constant development, with important antecedents in Argentina, the GSI assimilation system, and in particular its LETKF version, has not been tested in Argentina and is one of the original contributions of this thesis. 

The results obtained show that the assimilation of observations with high temporal and spatial frequency generates an important impact on the planetary boundary layer correcting the warm and dry bias present in the model and generating a better development of deep convection and precipitation for the case study. The assimilation of the radiance observations produced a better development of convection leading to an increase in accumulated precipitation. The ensemble forecast initialized from each experiment also showed improvements in the precipitation representation. Finally, the implementation of GOES-16 observation assimilation was shown to be possitive producing precipitation forecasts closer to the observed. In particular, the sensitivity experiments generated to analyze the impact of assimilating observations from the three water vapor channels showed that channel 10, associated with water vapor content at low levels, provides almost as much information as simultaneously assimilating the three water vapor channels, particularly when the observations are assimilated using a spatial resolution similar to that of the model (10 km). 

**Key words:** Data assimilation, Mesoescale, Convencional observations, Satellite observations, Forecasts 






