# Conclusiones generales y perspectivas futuras

## Conclusiones

Este trabajo representa un avance en el desarrollo de la asimilación de datos en escala regional y en consecuencia, en una mejor representación de los procesos convectivos que generan fenómenos con mayor impacto socioeconómico, como lluvias y vientos intensos, granizo y actividad eléctrica. También busca contribuir a la mejora de un sistema de alerta temprana sobre la ocurrencia de fenómenos meteorológicos extremos asociados a convección húmeda profunda. Es por esto que se pone el foco en la asimilación de observaciones de estaciones meteorológicas automáticas (EMA), vientos derivados de satélite y radianzas en cielos despejados, fuentes de observaciones con una gran resolución espacial y frecuencia temporal en una región donde la disponibilidad de observaciones convencionales es baja.  

En este trabajo se utilizó el modelo numérico WRF acoplado al sistema de asimilación GSI que es capaz de asimilar observaciones de EMA y radianzas gracias al modelo de transferencias radiativa CRTM que utiliza como operador de las observaciones. Sin embargo hasta ahora la última versión de GSI no era capaz de asimilar radianzas del sensor ABI a bordo del satélite geoestacionario GOES-16 que aporta observaciones con altísima resolución espacial y temporal. La implementación de las rutinas necesarias para ampliar las capacidad del sistema de asimilación a partirde trabajos previos de @lee2019 y @liu2019, es uno de los aportes técnicos principales de este trabajo. 

Los experimentos de asimilación de datos incluidos en este trabajo generan análisis horarios con 10 km de resolución horizontal utilizando la metodología de filtro de Kalman y un ensamble multifísica de 60 miembros. Además se generaron pronósticos por ensambles y deterministicos, todos para evaluar el impacto de la asimilación de distintos tipos de observaciones en la representación de un sistema convectivo de mesoescala (SCM) que se generó en el centro y norte de Argentina durante el 22 de noviembre de 2018. Este caso de estudio es de particular interés ya que forma parte de los casos de estudio de la campañana de campo RELAMPAGO donde se tomaron mediciones extraordinarias como sondeos con alta frecuencia temporal que son útiles para validar los experimentos.

De la comparación entre los experimentos y con observaciones independientes se puede ver que el impacto de las observaciones de EMA es de los más importantes. Una de las principales mejoras que se observa tanto en el análisis como en los pronósticos determinísticos es la representación de la temperatura y humedad en la capa límite, reduciendo el bias cálido y seco del modelo. El impacto de la asimilación también se extiende a la tropósfera principalmente en los periodos de convección más intensa. El aumento en el agua precipitable y la circulación meridional en los análisis condujo al desarrollo de convección más intensa y una mejor representación de la precipitación. Los pronósticos inicializados a partir del análisis, muestran además que el impacto se traslada a los pronósticos y perdura en el tiempo. De hecho, se observan mejoras entre el pronóstico que se inicializa a las 00 y el que se inicializa a las 06 UTC en la representación de la precipitación en parte debido a la asimilación de observaciones entre estos tiempos. 

El impacto de los vientos derivados de satélite en los análisis es mínimo en comparación con el impacto que genera la asimilación de observaciones de EMA y solo es apreciable en las componente del viento, principalmente en niveles medios y altos. Esto puede deberse al bajo número de observaciones asimiladas en niveles bajos o a una sobreestimación del error de las observaciones que lleva al sistema de asimilación a darle menos peso a la hora de generar el anaĺisis. Sin embargo, el impacto de estas observaciones es suficiente para generar una mejor representación de la precipitación tanto en el campo preliminar como en los pronósticos por ensambles, particularmente cuando se hace foco en probabilidades de pricipitación para umbrales altos. En estos pronósticos y el pronóstico determinísco en alta resolución, el inicio de la precipitación intensa coincide con lo observado pero esta decae ligeramente cuando se la compara con otros pronósticos.

La asimilación de radianzas en cielos despejados generó impactos en todos los niveles de la atmósfera, particularmente en la temperatura y humedad. Esto en parte se debe a que los disintos sensores y canales aportan información sobre estas variables en distintas capas de presión. Si bien se observa un ligero aumento del bias cálido y seco del modelo, reduciendo el impacto de las observaciones de EMA, el análisis genera un desarrollo de la convección adecuado que conduce a un aumento en la precipitación mayor a lo que se observa en otros experimentos. Por otro lado, en los pronósticos por ensambles inicializados a partir de los analisis con asimilación de radianzas de satélites polares subestima la precipitación en comparación con los pronósticos cuyas condiciones inciales tienen solo vientos derivados de satélite y EMA, aunque la ubica correctamente en el dominio. Esto podría deberse de una disminución de la humedad en niveles bajos que conduce a una atmósfera más estable. 

Las observaciones de los canales de vapor de agua de ABI producen impactos también en todos los niveles de la atmósfera y en algunos casos son similares a lo que generan las radianzas de satélites polares, por ejemplo reduciendo la humedad en la capa límite. Sin embargo, también producen impactos en niveles medios que ayudan al desarrollo de mayor inestabilidad y desarrollo de la convección. De la comparación con los sondeos de RELAMPAGO se destaca la mejora sustancial en la representaición de la humedad por encima de la capa límite donde se asimilan la mayor cantidad de observaciones. La representación de la precipitación tanto en el análisis como en el pronóstico determinístico es muy buena para umbrales bajos y se destaca la mejora respecto de otros experimentos en el área cubierta por precipitación y el desarrollo de la nubosidad. En estos experimentos, sin embargo, la precipitación se inicia ligeramente atrasada y la ubicación del SCM también se ubica por detrás de lo observado, esto puede estar asociado a la ubicación e intensidad del frente frío asociado a este sistema y la circulación en niveles bajos.

Finalmente, los experimentos con asimilación de observaciones de ABI, de satélites polares y aquel que incluye ambas fuentes de información permitieron evaluar el impacto de estas observaciones. Se observó que los resultados asociados a las observaciones de satelítes polares fueron iguales o peores en comparación con los que dieron los experimentos que si incluyeron observaciones de ABI. De hecho, la representación de la localización de la precipitación y el desarrollo de la convección fue mucho mejor en los pronósticos inicializados a partir de análisis con asimilación de radianzas en cielo despejado de ABI, eliminando convección espuria que generaron otros experimentos. Teniendo en cuenta esto, y al menos para este caso de estudio, no parece ser necesaria la asimilación de radianzas de satélites polares cuando se asimilan observaciones de ABI.

Algunos de los principales desafíos encontrados durante este trabajo de tesis están asociados al uso del sistema de asimilación GSI, sistema que no había sido utilizado previamente en Argentina. En este sentido fue necesario explorar las capacidades del sistema analizando el código y generando pruebas de asimilación con observaciones convencionales para evaluar su desempeño. Este sistema de asimilación, además, ingesta las observaciones en formato bufr por lo que fue necesario convertir las observaciones de EMA a este formato binario siguiendo las especificaciones definidas por el sistema para poder incluirlas en la asimilación. Trabajar con radianzas de satélites polares en un dominio regional también trae desafíos ya que las observaciones no están disponibles en todos los ciclos de asimilación y esto puede tener impactos importantes en el control de calidad y corrección del bias. Otro aspecto que representó un gran desafío es la asimilación de radianzas del sensor ABI, tanto desde el punto de vista técnico con la implementación de esta capacidad en el sistema de asimilación y la generación de los archivos en formato bufr como en la generación de pruebas y análisis preliminares para definir la mejor configuración del sistema de asimilación. Todo esto, sumado al alto costo computacional que requiere poder generar cada uno de los experimentos y la pruebas preliminares, limitó fuertemente la generación de experimentos para múltiples casos de estudio.

Este trabajo de tesis pone en evidencia la enorme potencialidad de la asimilación regional de observaciones con alta frecuencia temporal y resolución espacial que en algunos casos, no son incluidas en los pronósticos globales como son las observaciones de EMA y que puede contribuir a mejorar los sistema de pronósticos y la representación de fenómenos severos con importantes impactos socioeconómicos. Si bien es necesario seguir avanzando en este área y los desafíos técnicos son muchos, los avances tanto en el área de la asimilación de datos como la capacidad de cómputo en Argentina generan el contexto necesario para continuar el desarrollo de un sistema de pronósticos con asmilación de datos operativo.

## Perspectivas futuras

La asimilación de datos es un área en continuo avance. En particular la aplicación de la asimilación de datos en escala regional presenta muchos desafíos y la necesidad de seguir explorando y evaluando su impacto en la generación de pronósticos a corto plazo. En este punto es importante destacar una serie de preguntas para las que aún no se encontró respuesta o cuestiones que se desprenden del trabajo realizado y que podrían ser abordadas en trabajos futuros.

Si bien los resultados obtenidos con la asimilación de observaciones de EMA son muy prometedores, es importante continuar estudiando el impacto de la asimilación de estas observaciones en distintos casos de estudio que representen distintas situaciones atmosféricas. Teniendo en cuenta que en algunos casos se observó un impacto negativo asociado a la asimilación de observaciones de EMA, por ejemplo al comparar los pronósticos y análisis con los sondeos de RELAMPAGO, es importante avanazar en el desarrollo de un control de calidad robusto para estas observaciones previo a su asimilación. Por otro lado, es importante evaluar la magnitud de los errores de las observaciones usados ya que estos podrían ser mayor a lo estimado actualmente. Por un lado es posible que estas estaciones tengan menos controles de calidad, aumentando el error de las observaciones; y por el otro, que la alta frecuencia temporal y resolución espacial de la observaciones genere que sus errores estén correlacionados entre si. 

Sin embargo, para extender el uso de estas observaciones en este y otros ámbitos es importante establecer vinculos con las instituciones y organismos que generan las observaciones y aquellos que las utilizan para tareas de investigación u operativas. Por ejemplo, sería muy provechoso que las observaciones pudieran ser utilizadas operacionalmente por el Serivicio Meteorológico Nacional y en un futuro sean incluidas en los sistemas de informacion de la Organización Mundial de Meteorología para que puedan ser utilizadas a escana regional y global. Este trabajo es un ejemplo de cómo el uso de observaciones que no forman parte de las redes oficiales de información puede mejorar los pronósticos en la región y esperamos que ayude a sentar las bases necesarias para generar una política de datos que permita el intercambio de información entre las organizaciones. 

También es sorprendente el impacto positivo de los vientos derivados de satélite en los pronósticos de precipitación cuando en el análisis no se ven grandes diferencias. Será importante, entonces, entender mejor los impactos que producen estas observaciones y extender su uso a otros casos de estudio. Estas observaciones podrían ser de particular interés en el pronóstico de SCM donde la presencia de nubosidad la región permite obtener mayor cantidad de estimaciones de viento. Otro aspecto que sería deseable continuar estudiando es el impacto de las radianzas de satélites polares, particularmente de los sensores multiespectrales. Estos sensores aportan un gran volumen de observaciones en distintos niveles verticales que puede ser clave para representar distintos proceso atmosféricos, sin embargo es importante estudiar las características de los canales en detalle a fin de entender el impacto que generan y evitar la degradación del análisis por efectos de la superfice o correlaciones entre sus errores. 

La asimilación de observaciones de ABI mostró resultados muy prometedores en el desarrollo de la convección y la representación de la precipitación. Sería interesante en el futuro continuar realizando experimentos que aislen el impacto de cada canal de vapor de agua para entender mejor el rol que juega cada uno. También es importante evaluar nuevamente la necesidad o no de realizar correción de bias para estas observaciones y analizar posibles correlaciones entre los errores observacionales de los distintos canales. Un tema no desarrollado en este trabajo es la sensibilidad a la localización vertical de las radianzas. Estas observaciones abarcan toda la troposfera y parte de la estratosfera por lo que seria importante estudiar si cambios en la localización vertical, es decir, la capa de la atmósfera donde cada observación tiene influencia produce mejores resultados. Por otro lado, la asimilación de observaciones *all sky*, es decir, tanto en cielos despejados como nublados es el paso natural a seguir, que si bien introduce desafíos, particularmente en la estimación de los errores de las observaciones, muchas veces no lineaes, podría mejorar sustancialmente la representación de la convección en la región.

Es importante destacar un desafío que plantean el gran volumen de observaciones, particularmente de satélites, y la posible correlacion entre sus errores a los sistemas de asimilacion actuales. Si bien, estas correlaciones pueden ser estimadas a partir de los sistemas de asimilación (por ejemplo utilizando las estadísticas de Desroziers [@desroziers2005] para estimar la estructura de las correlaciones de los errores observacionales), el desafío también está en cómo considerar explicitamente las correlaciones tanto espaciales como entre los canales en los sistemas de asimilación. 

Asimismo, sería deseable avanzar con la asimilación de otras fuentes de observaciones como las de radio ocultamiento de GPS que ya son utilizados en por Centro de Previsão de Tempo e Estudos Climáticos en Brasil [@banos2019] u observaciones de radares que ya cuenta con importantes avances en el país [@maldonado2020; @maldonado2021]. El uso de otras metodologías para estimar el impacto relativo de las distintas fuentes de información, por ejemplo el *Ensemble Forecast Sensitivity to Observations* (EFSO, @hotta2017), pueden contribuir a cuantificar el impacto de las observaciones con mayor eficiencia. Sumado a esto, surge la necesidad de explorar la asimilación multiescala que permite la asimilación diferencial de observaciones, de acuerdo a la escala de lo que representan procesos que representan [@demoraes2020], mejorando la representación de procesos en distintas escalas. 

Por último, es importante mencionar el proyecto Pronóstico y Alerta de Eventos de Inundaciones Repentinas (PREVENIR) que comenzó en junio de 2022. Este proyecto contempla la colaboración entre instituciones de investigación de Japón y organismos científico-técnicos de
Argentina con el objetivo de desarrollar un sistema de pronóstico hidrometeorológico a corto plazo que busca mejorar el alerta temprana de eventos asociados a lluvias intensas en áreas densamente pobladas de Argentina. Entre otras cosas, el proyecto aplicará la asimilación de datos para generar pronósticos a corto plazo utilizando observaciones de EMA, radar y radianzas. En este sentido, la experiencia y conocimientos ganados a lo largo de este trabajo de tesis será de gran utilidad en el desarrollo del proyecto PREVENIR. 
